package com.example.crypto

import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import java.io.OutputStream

object PdfManager {
    fun createKeyPdf(mnemonic: List<String>, outputStream: OutputStream, accentColor: Int) {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = document.startPage(pageInfo)
        val canvas = page.canvas
        val paint = Paint()

        paint.color = accentColor
        paint.textSize = 60f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Crypto", 50f, 80f, paint)

        paint.textSize = 24f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        paint.alpha = 200
        canvas.drawText("SECURE RECOVERY KEY", 50f, 120f, paint)

        paint.strokeWidth = 2f
        paint.alpha = 255
        canvas.drawLine(50f, 140f, 545f, 140f, paint)

        paint.color = android.graphics.Color.BLACK
        paint.textSize = 16f
        var yPos = 200f
        val xCol1 = 50f
        val xCol2 = 300f

        mnemonic.forEachIndexed { index, word ->
            val number = index + 1
            paint.color = accentColor
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            canvas.drawText("$number.", if (index < 13) xCol1 else xCol2, yPos, paint)

            paint.color = android.graphics.Color.BLACK
            paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            val offset = paint.measureText("$number. ")
            canvas.drawText(word, (if (index < 13) xCol1 else xCol2) + offset, yPos, paint)

            if (index == 12) yPos = 200f else yPos += 30f
        }

        val copyStartY = 650f
        val maxWidth = 500f
        val startX = 50f

        paint.color = android.graphics.Color.LTGRAY
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 2f
        canvas.drawRect(40f, copyStartY - 30f, 555f, copyStartY + 100f, paint)

        paint.style = Paint.Style.FILL
        paint.color = android.graphics.Color.BLACK
        paint.textSize = 14f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("COPY-PASTE STRING (Select text below):", startX, copyStartY, paint)

        paint.typeface = Typeface.create(Typeface.MONOSPACE, Typeface.NORMAL)
        paint.textSize = 12f

        val words = mnemonic.joinToString(" ").split(" ")
        var currentLine = ""
        var currentY = copyStartY + 30f

        for (word in words) {
            val testLine = if (currentLine.isEmpty()) word else "$currentLine $word"
            val width = paint.measureText(testLine)

            if (width < maxWidth) {
                currentLine = testLine
            } else {
                canvas.drawText(currentLine, startX, currentY, paint)
                currentLine = word
                currentY += 20f
            }
        }
        if (currentLine.isNotEmpty()) {
            canvas.drawText(currentLine, startX, currentY, paint)
        }

        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
        paint.color = android.graphics.Color.GRAY
        paint.textSize = 12f
        canvas.drawText("Generated by Crypto App", 50f, 800f, paint)

        document.finishPage(page)
        document.writeTo(outputStream)
        document.close()
    }
}